kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio
  namespace: tsebra-home
  labels:
    app: minio

spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      # securityContext:
      #   capabilities:
      #     add:
      #       - NET_ADMIN
      containers:
        - name: minio
          image: minio/minio
          ports:
            - name: http-api
              containerPort: 9000
            - name: http-webui
              containerPort: 37935
            - name: ftp
              containerPort: 8021
          env:
            - name: MINIO_ACCESS_KEY
              value: JVHPHHVZ5ALC4398ZHJQCD
            - name: MINIO_SECRET_KEY
              value: bUQnd7UFy6dG50JoJovNabzj*Szzm35LB^04fwZ
            - name: MINIO_OPTS
              value: --ftp="address=:8021" --ftp="passive-port-range=30000-40000"
            # - name: MINIO_DOMAIN
            #   value: mineo.tsebra.com
          volumeMounts:
            - name: minio-data
              mountPath: /data
          command:
            [
              "/bin/sh",
              "-c",
              'minio server /data --console-address ":9002" --ftp "address=:8021" --ftp "passive-port-range=30000-40000"',
            ]
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-data
