apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mineo-webui
  namespace: tsebra-home
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: mineo-webui
      port:
        number: 80
  tls:
    - hosts:
        - mineo-webui.tsebra.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mineo-api
  namespace: tsebra-home
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: mineo-api
      port:
        number: 80
