apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mineo
  namespace: tsebra-home
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: mineo
      port:
        number: 80
  tls:
    - hosts:
        - mineo
