apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mineo-api
  namespace: tsebra-home
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`mineo.tsebra-home.de`)
      services:
        - name: mineo-api
          port: 80
  tls:
    certResolver: default
