apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-api
  namespace: tsebra-home
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`minio-api.tsebra-home.de`)
      services:
        - name: minio-api
          port: 9000
    - kind: Rule
      match: Host(`minio-webui.tsebra-home.de`)
      services:
        - name: minio-webui
          port: 37935
  tls:
    certResolver: default
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: minio-ftp
  namespace: tsebra-home
spec:
  entryPoints:
    - ftp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: minio-ftp
          port: 8021
