apiVersion: v1
kind: Service
metadata:
  name: mineo
  namespace: tsebra-home
  labels:
    run: mineo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9001
    protocol: TCP
    name: http
  selector:
    run: mineo