apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-config
  namespace: tsebra-home
  labels:
    app: nfs
data:
  NFS_EXPORT_0: /mnt/normal-scans *
  NFS_EXPORT_1: /mnt/paperless-scans *(rw,no_subtree_check)
  NFS_EXPORT_2: /mnt/nas-outbound 192.168.178.0/24(rw,no_subtree_check)
  # NFS_EXPORT_3: /nfs/nas-test *(rw,no_subtree_check)
  # NFS_EXPORT_4: /mnt/disk1        192.168.6.0/24(ro,async,subtree_check,insecure,fsid=11)
