apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs
  namespace: tsebra-home
spec:
  selector:
    matchLabels:
      run: nfs
  replicas: 1
  template:
    metadata:
      labels:
        run: nfs
    spec:
      containers:
        - image: erichough/nfs-server
          name: nfs
          ports:
            - containerPort: 2049
          env:
            - name: NFS_EXPORT_0
              value: "/normal-scans"
            - name: NFS_EXPORT_1
              value: "/paperless-scans"
            - name: NFS_EXPORT_2
              value: "/nas-outbound"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nfs-data
