apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs
  namespace: tsebra-home
spec:
  selector:
    matchLabels:
      app: nfs
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
        - image: pedroetb/nfs-server
          name: nfs
          ports:
            - containerPort: 2049
          env:
            - name: NFS_EXPORT_0
              value: /nfs/normal-scans *(rw,no_subtree_check)
            - name: NFS_EXPORT_1
              value: /nfs/paperless-scans *(rw,no_subtree_check)
            - name: NFS_EXPORT_2
              value: /nfs/nas-outbound *(rw,no_subtree_check)
          volumeMounts:
            - name: data
              mountPath: /nfs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nfs-data
