apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs
  namespace: tsebra-home
spec:
  selector:
    matchLabels:
      app: nfs
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
        - image: pedroetb/nfs-server
          name: nfs
          ports:
            - containerPort: 2049
          envFrom:
            - configMapRef:
                name: nfs-config
          volumeMounts:
            - name: data
              mountPath: /nfs
              subPath: normal-scans
            - name: data
              mountPath: /nfs
              subPath: paperless-scans
            - name: data
              mountPath: /nfs
              subPath: nas-outbound
          securityContext:
            privileged: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nfs-data
