apiVersion: v1
kind: Service
metadata:
  name: nfs
  namespace: tsebra-home
  labels:
    run: nfs
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - port: 2049
    targetPort: 2049
    protocol: TCP
    name: nfs
  selector:
    run: nfs