apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: tailscale
  name: operator-oauth
  namespace: tsebra-home
stringData:
  clientId: {{ placeholder "clientId" }}
  clientSecret: {{ placeholder "clientSecret" }}