apiVersion: v1
kind: Service
metadata:
  name: fritz-box-service
  namespace: tsebra-home
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ExternalName
  externalName: fritz.box
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fritz-box
  namespace: tsebra-home
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`fritz-box.tsebra-home.de`)
      services:
        - name: fritz-box-service
          port: 80
  tls:
    certResolver: default