apiVersion: v1
kind: Service
metadata:
  name: home-assistant-vm
  namespace: tsebra-home
spec:
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123

  type: ExternalName
  externalName: localhost
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-vm
  namespace: tsebra-home
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`home-assistant-vm.tsebra-home.de`)
      middlewares:
        - name: traefik-wol-nas
          namespace: tsebra-home
      services:
        - name: home-assistant-vm
          port: 8123
  tls:
    certResolver: default
