apiVersion: v1
kind: Service
metadata:
  name: synology-minio-api
  namespace: tsebra-home
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090

  type: ExternalName
  externalName: nas.fritz.box
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: synology-minio-api
  namespace: tsebra-home
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`minio-nas.tsebra-home.de`)
      middlewares:
        - name: traefik-wol-nas
          namespace: tsebra-home
      services:
        - name: synology-minio-api
          port: 9090
  tls:
    certResolver: default
---
apiVersion: v1
kind: Service
metadata:
  name: synology-minio-ui
  namespace: tsebra-home
spec:
  ports:
    - protocol: TCP
      port: 9099
      targetPort: 9099

  type: ExternalName
  externalName: nas.fritz.box
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: synology-minio-ui
  namespace: tsebra-home
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`minio-nas-ui.tsebra-home.de`)
      services:
        - name: synology-minio-ui
          port: 9099
  tls:
    certResolver: default
