apiVersion: apps/v1
kind: Deployment
metadata:
  name: wol-api
  namespace: tsebra-home
spec:
  selector:
    matchLabels:
      app: wol-api
  replicas: 1
  template:
    metadata:
      labels:
        app: wol-api
    spec:
      # nodeName: tsebra-k8s
      hostNetwork: true #needs to be on the same network as the server
      containers:
        - image: fbrak/docker-wol-api:arm64 # custom image build for arm based on https://github.com/rix1337/WakeOnLAN-API/blob/main/docker/Dockerfile
          name: wol-api
          ports:
            - containerPort: 8111
              hostPort: 8111
          env:
            - name: PORT
              value: "8111"
---
apiVersion: v1
kind: Service
metadata:
  name: wol-api
  namespace: tsebra-home
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8111
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-wol-nas
  namespace: tsebra-home
spec:
  plugin:
    traefik-wol:
      startUrl: http://tsebra-k8s.tsebra-home.de:8111/wol/90:09:D0:36:34:BD
      startMethod: GET
      numRetries: 5
      requestTimeout: 60
      HealthCheck: http://192.168.178.94:5000
