apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: tsebra-home

spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: dashboard
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
  selector:
    app: traefik