apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: tsebra-home

spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 8080
      targetPort: dashboard
    - port: 80
      targetPort: web
  selector:
    app: traefik