apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: tsebra-home
  labels:
    app: home-assistant
data:
  configuration.yaml: |
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 192.168.178.66
