apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-root
  namespace: tsebra-home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
