kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-assistant
  namespace: tsebra-home
  labels:
    app: home-assistant

spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      # securityContext:
      #   capabilities:
      #     add:
      #       - NET_ADMIN
      serviceAccountName: home-assistant
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:stable
          ports:
            - name: http
              containerPort: 8123
