apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: tsebra-home
spec:
  entryPoints:
    - http
  routes:
    - kind: Rule
      match: Host(`home-assistant.tsebra-home.de`)
      services:
        - name: home-assistant
          port: 80
