apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: tsebra-home
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`home-assistant.tsebra-home.de`)
      services:
        - name: home-assistant
          port: 8123
  tls:
    certResolver: default
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-public
  namespace: tsebra-home
  annotations:
    tailscale.com/funnel: "true"
spec:
  defaultBackend:
    service:
      name: home-assistant-public
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - home-assistant
