apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: tsebra-home
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`home-assistant.tsebra-home.de`)
      services:
        - name: home-assistant
          port: 8123
  tls:
    certResolver: default
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-public
  namespace: tsebra-home
  annotations:
    kubernetes.io/ingress.class: traefik-public
  labels:
    traefik-public: true
spec:
  entryPoints:
    - http
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      services:
        - name: home-assistant
          port: 8123
  tls:
    certResolver: default
