apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: tsebra-home

spec:
  type: ClusterIP
  ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
      name: http
  selector:
    app: home-assistant
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-public
  namespace: tsebra-home

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8123
      protocol: TCP
      name: http
  selector:
    app: home-assistant
