apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homematic
  namespace: tsebra-home
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`homematic.tsebra-home.de`)
      services:
        - name: homematic
          port: 80
  tls:
    certResolver: default
---
