apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: tsebra-home
  labels:
    app: paperless
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: paperless
