apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: paperless
      port:
        number: 8000
  tls:
    - hosts:
        - paperless