apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless
  namespace: tsebra-home
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`paperless.tsebra-home.de`)
      services:
        - name: paperless
          port: 80
  tls:
    certResolver: default
