apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: tsebra-home
spec:
  loadBalancerClass: tailscale
  type: LoadBalancer
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: paperless
  tls:
    - hosts:
        - paperless
