# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: paperless
#   namespace: tsebra-home
# spec:
#   ingressClassName: tailscale
#   defaultBackend:
#     service:
#       name: paperless
#       port:
#         number: 80
#   tls:
#     - hosts:
#         - paperless
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless
  namespace: tsebra-home
spec:
  entryPoints:
    - http
  routes:
    - kind: Rule
      match: Host(`paperless.tsebra-home.de`)
      services:
        - name: paperless
          port: 80
