apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argo-cd
  namespace: argocd
spec:
  repo: https://argoproj.github.io/argo-helm
  version: 2.14.2
  chart: argo-cd
  targetNamespace: argocd
  valuesContent: |-
    service:
      type: LoadBalancer
    metrics:
      enabled: true
