apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-static
  namespace: traefik-system
  labels:
    app: traefik
data:
  traefik.yml: |
    global:
      checkNewVersion: false
      sendAnonymousUsage: true
    entryPoints:
      http:
        address: :80
        http:
          redirections:
            entryPoint:
              to: https
              scheme: https
              permanent: false
              priority: 1
      https:
        address: :443
        http:
          tls: {}
      nfs:
        address: :2049
      ftp:
        address: :21
      smb:
        address: :445
    providers:
      kubernetesCRD: {}
    #  ingressClass: traefik-crd
    api:
      # dashboard: true
      insecure: true
    ping:
      entryPoint: http
    log:
      level: INFO
    certificatesResolvers:

      default:
        acme:
          storage: /acme/acme.json
          dnsChallenge:
            provider: cloudflare
    experimental:
      plugins:
        traefik-wol:
          moduleName: "github.com/MarkusJx/traefik-wol"
          version: "v0.1.1"
