apiVersion: apps/v1
kind: Deployment
metadata:
  name: wol-api
  namespace: tsebra-home
spec:
  selector:
    matchLabels:
      app: wol-api
  replicas: 1
  template:
    metadata:
      labels:
        app: wol-api
    spec:
      hostNetwork: true #needs to be on the same network as the server
      containers:
        - image: fbrak/docker-wol-api:latest # custom image build for arm based on https://github.com/rix1337/WakeOnLAN-API/blob/main/docker/Dockerfile
          name: wol-api
          ports:
            - containerPort: 8111
          env:
            - name: PORT
              value: "8111"
---
apiVersion: v1
kind: Service
metadata:
  name: wol-api
  namespace: tsebra-home
spec:
  ports:
    - protocol: TCP
      port: 8111
      targetPort: 8111
  type: ClusterIP
