apiVersion: apps/v1
kind: Deployment
metadata:
  name: wol-api
  namespace: tsebra-home
spec:
  selector:
    matchLabels:
      app: wol-api
  replicas: 1
  template:
    metadata:
      labels:
        app: wol-api
    spec:
      hostNetwork: true #needs to be on the same network like the servers it should wake up
      containers:
        - image: rix1337/docker-wol-api:latest
          name: wol-api
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: wol-api
  namespace: tsebra-home
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
