apiVersion: v1
kind: Service
metadata:
  name: minio-webui
  namespace: tsebra-home
spec:
  type: ClusterIP
  ports:
    - port: 9002
      targetPort: 9002
      protocol: TCP
      name: http-webui
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-api
  namespace: tsebra-home
  labels:
    app: minio
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http-api
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-ftp
  namespace: tsebra-home
spec:
  type: ClusterIP
  ports:
    - port: 8021
      targetPort: 8021
      protocol: TCP
      name: ftp
  selector:
    app: minio
