apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-static
  namespace: traefik-public
  labels:
    app: traefik
data:
  traefik.yml: |
    accessLog: {}
    metrics:
     otlp: {}
    tracing: {}

    global:
      checkNewVersion: false
      sendAnonymousUsage: true
    entryPoints:
      http:
        address: :80
        http:
          # redirections:
          #   entryPoint:
          #     to: https
          #     scheme: https
          #     permanent: false
          #     priority: 1
      # https:
      #   address: :443
      #   http:
      #     tls: {}
    providers:
      kubernetesCRD:
        allowExternalNameServices: true
        labelSelector: "traefik-public=true"
    #  ingressClass: traefik-crd
    kubernetes:
      ingressclass: traefik-public
    api:
      # dashboard: true
      insecure: true

    ping:
      entryPoint: http
    log:
      level: INFO
    # certificatesResolvers:

    #   default:
    #     acme:
    #       storage: /acme/acme.json
    #       dnsChallenge:
    #         provider: cloudflare
    # experimental:
    #   plugins:
    #     traefik-wol:
    #       moduleName: "github.com/MarkusJx/traefik-wol"
    #       version: "v0.1.1"
