apiVersion: v1
kind: Service
metadata:
  name: traefik-public
  namespace: traefik-public
spec:
  selector:
    app: traefik-public
  ports:
    - port: 80
      protocol: TCP
      name: http
    # - port: 443
    #   protocol: TCP
    #   name: https
    # - port: 9000
    #   protocol: TCP
    #   name: dashboard
    # - port: 2049
    #   protocol: TCP
    #   name: nfs
    # - port: 445
    #   protocol: TCP
    #   name: smb
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-public
  namespace: traefik-public
spec:
  defaultBackend:
    service:
      name: traefik-public
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - traefik-public
